### ISSUE TITLE
:return-keys option requires a vector of strings instead of keywords

### ISSUE THREAD

**Issue by MigrenusMaximus** [seancorfield/next-jdbc#102]
Passing a vector of qualified or unqualified keywords to the `:return-keys` option throws an `IllegalArgumentException`.
Passing a vector of strings produces the expected behavior.

This is in contrast to the official docs which state that `:return-keys` accepts a vector of keywords as its argument.

**Examples**

Required namespaces are as follows:
```clojure
[next.jdbc :as jdbc]
[next.jdbc.sql :as sql]
[next.jdbc.result-set :as rs]
```

**Produces `IllegalArgumentException`**
```clojure
(with-open [conn (jdbc/get-connection spec)]
     (sql/insert! conn
       :reporting.lookup_query
       lookup-query
       {:builder-fn rs/as-unqualified-maps
        :return-keys [:id]}))
```

**Produces `IllegalArgumentException`**
```clojure
(with-open [conn (jdbc/get-connection spec)]
     (sql/insert! conn
       :reporting.lookup_query
       lookup-query
       {:builder-fn rs/as-unqualified-maps
        :return-keys [:lookup_query/id]}))
```

**Produces map with the `id` key only (expected behavior)**
```clojure
(with-open [conn (jdbc/get-connection spec)]
     (sql/insert! conn
       :reporting.lookup_query
       lookup-query
       {:builder-fn rs/as-unqualified-maps
        :return-keys ["id"]}))
```

**Stacktraces**
```
java.lang.IllegalArgumentException: array element type mismatch
	at java.base/java.lang.reflect.Array.set(Native Method) ~[na:na]
	at clojure.lang.RT.seqToTypedArray(RT.java:1776) ~[clojure-1.10.1.jar:na]
	at clojure.core$into_array.invokeStatic(core.clj:3454) ~[clojure-1.10.1.jar:na]
	at clojure.core$into_array.invoke(core.clj:3443) ~[clojure-1.10.1.jar:na]
	at next.jdbc.prepare$string_array.invokeStatic(prepare.clj:80) ~[na:na]
	at next.jdbc.prepare$string_array.invoke(prepare.clj:78) ~[na:na]
	at next.jdbc.prepare$create.invokeStatic(prepare.clj:101) ~[na:na]
	at next.jdbc.prepare$create.invoke(prepare.clj:82) ~[na:na]
	at next.jdbc.result_set$eval12742$fn__12747.invoke(result_set.clj:578) ~[na:na]
	at next.jdbc.protocols$eval12076$fn__12077$G__12065__12086.invoke(protocols.clj:33) ~[na:na]
	at next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:241) ~[na:na]
	at next.jdbc$execute_one_BANG_.invoke(jdbc.clj:225) ~[na:na]
	at next.jdbc.sql$insert_BANG_.invokeStatic(sql.clj:40) ~[na:na]
	at next.jdbc.sql$insert_BANG_.invoke(sql.clj:31) ~[na:na]
	at erporting.domain.lookup_query.db$create_BANG_.invokeStatic(db.clj:42) ~[na:na]
```

**project.clj**
```clojure
[org.clojure/clojure "1.10.1"]
[hikari-cp "2.10.0" :exclusions [com.zaxxer/HikariCP]]
[com.zaxxer/HikariCP "3.4.2" :exclusions [org.slf4j/slf4j-api]]
[org.postgresql/postgresql "42.2.10"]
[seancorfield/next.jdbc "1.0.405"]
```

**Environment:**
 - OS: [Ubuntu 18.04]
 - Java Version: [openjdk 11.0.6 2020-01-14]
 - Clojure Version: [1.10.1]
 - Database: [psql (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)]
 - Driver Library Version: [org.postgresql/postgresql "42.2.10"]

**Comment by seancorfield** [comment]
Thank you. Fixed on **master**.
