### ISSUE TITLE
GraalVM native image

### ISSUE THREAD

**Issue by nenadalm** [seancorfield/next-jdbc#156]
**Describe the bug**
Library doesn't work with native-image

**To Reproduce**

**deps.edn**
```edn
{:paths ["."]
 :deps {org.clojure/clojure {:mvn/version "1.10.2-rc3"}
        seancorfield/next.jdbc {:mvn/version "1.1.613"}
        org.postgresql/postgresql {:mvn/version "42.2.18"}}
 :aliases {:next-jdbc-native-image
           {:extra-deps
            {luchiniatwork/cambada {:mvn/version "1.0.5"}}
            :main-opts ["-m" "cambada.native-image"
                        "--image-name" "next-jdbc"
                        "-m" "nextjdbc"
                        "-O" "-initialize-at-run-time=org.postgresql.sspi.SSPIClient"]}
           :jdbc-native-image
           {:extra-deps
            {luchiniatwork/cambada {:mvn/version "1.0.5"}}
            :main-opts ["-m" "cambada.native-image"
                        "--image-name" "jdbc"
                        "-m" "jdbc"
                        "-O" "-initialize-at-run-time=org.postgresql.sspi.SSPIClient"]}}}
```

**jdbc.clj**
```clojure
(ns jdbc
  (:gen-class))

(defn -main []
  (with-open [ds (java.sql.DriverManager/getConnection "jdbc:postgresql://127.0.0.1/postgres?user=postgres&password=postgres")
              st (.createStatement ds)
              rs (.executeQuery st "SELECT version()")]
    (.next rs)
    (println (.getString rs "version"))))
```

**nextjdbc.clj**
```clojure
(ns nextjdbc
  (:gen-class)
  (:require
   [next.jdbc :as jdbc]))

(defn -main []
  (let [ds (jdbc/get-datasource {:jdbcUrl "jdbc:postgresql://127.0.0.1/postgres?user=postgres&password=postgres"})]
    (-> (jdbc/execute-one! ds ["SELECT version()"])
        :version
        println)))
```

```shell
$ clj -M:jdbc-native-image # compiles ok, resulting binary prints postgres version
$ clj -M:next-jdbc-native-image # does not compile
```

**Expected behavior**

Code using this library can be compiled by native-image.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.9.1" 2020-11-04
 - Clojure Version: "1.10.2-rc3"

**Additional context**

I was creating small script that does one call to db and I found that this library doesn't work with native-image, so I just used jdbc directly for the simple case. As I couldn't find any mention of it in readme or existing issues, I decided to report it. Function `jdbc/execute-one!` in the example causes it to not compile as it compiles just fine when it is removed.

**Comment by borkdude** [comment]
We are using next.jdbc in pod-babashka-postgresql and pod-babashka-hsqldb, both are compiled with GraalVM.

Both seem to work with 1.0.613:

https://app.circleci.com/pipelines/github/babashka/babashka-sql-pods/94/workflows/f6ef7d48-a856-44f4-b083-2aac2a350b85/jobs/300

https://app.circleci.com/pipelines/github/babashka/babashka-sql-pods/94/workflows/f6ef7d48-a856-44f4-b083-2aac2a350b85/jobs/299

although we haven't tested `jdbc/execute-one!`. I'll try to add that var as well.

**Comment by borkdude** [comment]
@nenadalm It's likely that you are missing some config which makes postgres work correctly with native-image.

This is how we build. Note the arg `"--initialize-at-run-time=org.postgresql.sspi.SSPIClient"`:

```
$GRAALVM_HOME/bin/native-image \
    -jar "$JAR" \
    -H:Name="$POD_NAME" \
    -H:+ReportExceptionStackTraces \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    "-H:IncludeResources=POD_BABASHKA_SQL_VERSION" \
    -H:ReflectionConfigurationFiles="$POD_REFLECTION_CONFIG" \
    --initialize-at-build-time  \
    -H:Log=registerResource: \
    "-H:EnableURLProtocols=http,https" \
    "--enable-all-security-services" \
    "-H:+JNI" \
    --verbose \
    --no-fallback \
    --no-server \
    --report-unsupported-elements-at-runtime \
    "-H:IncludeResources=org/hsqldb/.*\.properties" "-H:IncludeResources=org/hsqldb/.*\.sql" \
    "--initialize-at-run-time=org.postgresql.sspi.SSPIClient" \
    "-J-Xmx4500m"
```

and this is our reflection config:

```
[{"name": "org.postgresql.jdbc.PgConnection",
  "methods" : [{"name":"close"}]}]
```

**Comment by borkdude** [comment]
Tested adding `execute-one!` and worked perfectly.

**Comment by seancorfield** [comment]
Thanks for checking that out @borkdude !

@nenadalm I'll keep this open for a few days, so you can let us know if this information helps you, but I'll close it out as "unable to repro" next week, based on Babashka successfully using next.jdbc with GraalVM.

**Comment by nenadalm** [comment]
@borkdude 
I see that you use `--report-unsupported-elements-at-runtime` which "fixes" the problem, by (to my understanding) replacing problematic parts of code with error reporting (instead of crashing during compilation):

> --report-unsupported-elements-at-runtime: report the usage of unsupported methods and fields at runtime when they are accessed the first time, instead of an error during an image building.
(https://www.graalvm.org/reference-manual/native-image/Options/)

so that if problematic part is accessed at runtime, that part won't work as programmed.

**Comment by borkdude** [comment]
@nenadalm I don't think this is a specific problem to next.jdbc, I think all native-image projects in Clojure need this when using 1.10.2-rc3. You should write tests to verify if your image works the way you expect it to. I think the unsupported elements are related to dynamic class loading, which is unsupported in GraalVM native-image. It would help if your error reporting concerning this issue was more detailed, since I could not understand if your native-image problem was next.jdbc specific. Please post error messages, etc.

**Comment by nenadalm** [comment]
@borkdude the error is here (it mentions some dynamic class loading you mentioned):
```
$ GRAALVM_HOME=/opt/graalvm/graalvm-ce-java11-21.0.0/ clj -M:next-jdbc-native-image
Cleaning target
Creating target/classes
  Compiling jdbc
  Compiling nextjdbc
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Creating target/next-jdbc
ERROR! Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
Call path from entry point to clojure.lang.DynamicClassLoader.defineClass(String, byte[], Object): 
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:45)
	at clojure.core$get_proxy_class.invokeStatic(core_proxy.clj:288)
	at clojure.core$get_proxy_class.doInvoke(core_proxy.clj:276)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.tools.logging.proxy$java.io.ByteArrayOutputStream$ff19274a.flush(Unknown Source)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
Call path from entry point to clojure.lang.DynamicClassLoader.defineClass(String, byte[], Object): 
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:45)
	at clojure.core$get_proxy_class.invokeStatic(core_proxy.clj:288)
	at clojure.core$get_proxy_class.doInvoke(core_proxy.clj:276)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.tools.logging.proxy$java.io.ByteArrayOutputStream$ff19274a.flush(Unknown Source)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
Call path from entry point to clojure.lang.DynamicClassLoader.defineClass(String, byte[], Object): 
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:45)
	at clojure.core$get_proxy_class.invokeStatic(core_proxy.clj:288)
	at clojure.core$get_proxy_class.doInvoke(core_proxy.clj:276)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.tools.logging.proxy$java.io.ByteArrayOutputStream$ff19274a.flush(Unknown Source)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
	... 8 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:187)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:409)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4345)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:119)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4339)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1700)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5404)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3436)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3243)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1109)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1003)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	... 5 more
Error: Image build request failed with exit status 1
```

**Comment by borkdude** [comment]
@nenadalm You can visit https://github.com/lread/clj-graal-docs for more information on GraalVM and Clojure or hop by in the #graalvm channel on Clojurians Slack. I think we can close this issue as non-next.jdbc specific @seancorfield.

**Comment by nenadalm** [comment]
> I think all native-image projects in Clojure need this when using 1.10.2-rc3

I was able to successfuly compile code with these libraries:
```edn
{org.clojure/clojure {:mvn/version "1.10.2-rc3"}
 org.martinklepsch/clj-http-lite {:mvn/version "0.4.3"}
 metosin/jsonista {:mvn/version "0.3.0"}
 expound/expound {:mvn/version "0.8.7"}
 org.postgresql/postgresql {:mvn/version "42.2.18"}
 org.clojure/data.xml {:mvn/version "0.0.8"}}
```
(also I used spec there). So some part of Clojure seems to be ok with native-image. I'll definitely read the link you provided. Thanks. Also I am already in the `#graalvm` channel.

I am closing the issue then.
