### ISSUE TITLE
Username cannot be set when using HikariDataSource connection pool library

### ISSUE THREAD

**Issue by danielkyu** [seancorfield/next-jdbc#83]
**Describe the bug**
According to the documentation [here](https://github.com/seancorfield/next-jdbc/blob/a2ba8ff780b602bc90b8e9f264821e96e638c63c/doc/all-the-options.md#datasources-and-connections), one should be able to specify the username for the connection via the `:user` key in the db-spec map. However, when using the Hikari connecting pool library, it appears that the username property is not being respected, unless one manually constructs the JDBC URL containing the username and password as parameters.

**To Reproduce**
This was an excerpt from locally testing on my machine...

1. Run an instance of CockroachDB (or any other Postgres compatible server) locally on port 26257.
2. Execute the following in the REPL.
```clojure
;; Does not work...
my.app> (def pool (jdbc-conn/->pool HikariDataSource {:dbtype "postgres"
                                                      :dbname "test"
                                                      :host "localhost"
                                                      :port 26257
                                                      :user "root"
                                                      :password ""}))

#'my.app/pool
my.app> (def conn (.getConnection pool))
Syntax error (PSQLException) compiling def at (form-init1602917805005856724.clj:77:26).
ERROR: password authentication failed for user daniel

;; Works
my.app> (def pool (jdbc-conn/->pool HikariDataSource
                                    {:jdbcUrl "jdbc:postgresql://localhost:26257/test?user=root&password="}))
#'my.app/pool
my.app> (def conn (.getConnection pool))
#'my.app/conn
```

**Expected behavior**
Rather than attempt to connect via the `daniel` user (which does not exist), a successful connection should have been established using the `root` user.

**Stacktraces**
```

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (11 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling form-init1602917805005856724.clj at (98:26)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 98,
                   :column 26,
                   :source "form-init1602917805005856724.clj",
                   :symbol def}
             Compiler.java:  470  clojure.lang.Compiler$DefExpr/eval
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7131  clojure.lang.Compiler/eval
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  414  clojure.main/repl/read-eval-print/fn
                  main.clj:  414  clojure.main/repl/read-eval-print
                  main.clj:  435  clojure.main/repl/fn
                  main.clj:  435  clojure.main/repl
                  main.clj:  345  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  748  java.lang.Thread/run

1. Caused by org.postgresql.util.PSQLException
   ERROR: password authentication failed for user daniel

ConnectionFactoryImpl.java:  520  org.postgresql.core.v3.ConnectionFactoryImpl/doAuthentication
ConnectionFactoryImpl.java:  141  org.postgresql.core.v3.ConnectionFactoryImpl/tryConnect
ConnectionFactoryImpl.java:  192  org.postgresql.core.v3.ConnectionFactoryImpl/openConnectionImpl
    ConnectionFactory.java:   49  org.postgresql.core.ConnectionFactory/openConnection
         PgConnection.java:  211  org.postgresql.jdbc.PgConnection/<init>
               Driver.java:  458  org.postgresql.Driver/makeConnection
               Driver.java:  260  org.postgresql.Driver/connect
     DriverDataSource.java:  121  com.zaxxer.hikari.util.DriverDataSource/getConnection
             PoolBase.java:  353  com.zaxxer.hikari.pool.PoolBase/newConnection
             PoolBase.java:  201  com.zaxxer.hikari.pool.PoolBase/newPoolEntry
           HikariPool.java:  473  com.zaxxer.hikari.pool.HikariPool/createPoolEntry
           HikariPool.java:  562  com.zaxxer.hikari.pool.HikariPool/checkFailFast
           HikariPool.java:  115  com.zaxxer.hikari.pool.HikariPool/<init>
     HikariDataSource.java:  112  com.zaxxer.hikari.HikariDataSource/getConnection
NativeMethodAccessorImpl.java:   -2  sun.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  sun.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  498  java.lang.reflect.Method/invoke
            Reflector.java:  167  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:  438  clojure.lang.Reflector/invokeNoArgInstanceMember
             Compiler.java: 1177  clojure.lang.Compiler$InstanceFieldExpr/eval
             Compiler.java:  457  clojure.lang.Compiler$DefExpr/eval
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7131  clojure.lang.Compiler/eval
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  414  clojure.main/repl/read-eval-print/fn
                  main.clj:  414  clojure.main/repl/read-eval-print
                  main.clj:  435  clojure.main/repl/fn
                  main.clj:  435  clojure.main/repl
                  main.clj:  345  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  748  java.lang.Thread/run
```

**project.clj/deps.edn**
Applicable dependencies...
- [com.zaxxer/HikariCP "3.4.1"]
- [org.clojure/clojure "1.10.0"]
- [org.postgresql/postgresql "42.2.9"]
- [seancorfield/next.jdbc "1.0.12"]

**Environment (please complete the following information):**
 - OS: Mac OSX 10.14.6
 - Java Version: Oracle Java 1.8.0_172
 - Clojure Version: 1.10.0
 - Database: CockroachDB v19.2.2
 - Driver Library Version: [org.postgresql/postgresql "42.2.9"]

**Additional context**
None.

**Comment by seancorfield** [comment]
Per the documentation https://cljdoc.org/d/seancorfield/next.jdbc/1.0.12/doc/getting-started#connection-pooling

"Some important notes regarding HikariCP:

* Authentication credentials must use :username (if you are using c3p0 or regular, non-pooled, connections, then the db-spec hash map must contain :user)."

**Comment by danielkyu** [comment]
From what it looks like, it appears as if this only affects `jdbc.connection/->pool` when `HikariDataSource` is used as `ComboPooledDataSource` `[com.mchange/c3p0 "0.9.5.5"]` does not appear to suffer this issue.

```clojure
my.app> (def pool (jdbc-conn/->pool ComboPooledDataSource {:dbtype "postgres"
                                                           :dbname "test"
                                                           :host "localhost"
                                                           :port 26257
                                                           :user "root"
                                                           :password ""}))
Dec 21, 2019 9:11:59 PM com.mchange.v2.c3p0.C3P0Registry 
INFO: Initializing c3p0-0.9.5.5 [built 11-December-2019 22:18:33 -0800; debug? true; trace: 10]
#'my.app/pool
my.app> (def conn (.getConnection pool))
Dec 21, 2019 9:12:08 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge16na7c7p2tytaa7xj|a77f8fc, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> null, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge16na7c7p2tytaa7xj|a77f8fc, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:postgresql://localhost:26257/test, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
#'my.app/conn
```

I think the problem stems from [this particular line of code](https://github.com/seancorfield/next-jdbc/blob/master/src/next/jdbc/connection.clj#L226). If my understanding is correct, it's creating a new instance of the provided class and taking the properties from the `etc` map (of which `user` and `password` should be a part of) and using reflection at some point to invoke the appropriate setters. Looking at the Javadocs for these two classes then, it seems that [HikariDataSource](https://javadoc.io/doc/com.zaxxer/HikariCP/latest/com/zaxxer/hikari/HikariDataSource.html) has its setter called [`setUsername()`](https://javadoc.io/doc/com.zaxxer/HikariCP/latest/com/zaxxer/hikari/HikariConfig.html#setUsername-java.lang.String-) while [ComboPooledDataSource](https://www.mchange.com/projects/c3p0/apidocs/com/mchange/v2/c3p0/ComboPooledDataSource.html) has its setter called [`setUser()`](https://www.mchange.com/projects/c3p0/apidocs/com/mchange/v2/c3p0/AbstractComboPooledDataSource.html#setUser-java.lang.String-). This explains why the `db-spec` map is accepted by C3P0 but not Hikari. Essentially for `HikariDataSource` it would be as if the setter was never invoked in the first place since `user` does not map to `username`.

As an experiment, I've changed the `db-spec` map to use `username` instead of `user`.
```clojure
;; Hikari
my.app> (def pool (jdbc-conn/->pool HikariDataSource {:dbtype "postgres"
                                                      :dbname "test"
                                                      :host "localhost"
                                                      :port 26257
                                                      :username "root"
                                                      :password ""}))
#'my.app/pool
my.app> (def conn (.getConnection pool))
#'my.app/conn


;; C3P0
my.app> (def pool (jdbc-conn/->pool ComboPooledDataSource {:dbtype "postgres"
                                                           :dbname "test"
                                                           :host "localhost"
                                                           :port 26257
                                                           :username "root"
                                                           :password ""}))
#'my.app/pool
my.app> (def conn (.getConnection pool))
Dec 21, 2019 9:12:20 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge16na7c7p2tytaa7xj|2ed81458, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> null, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge16na7c7p2tytaa7xj|2ed81458, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:postgresql://localhost:26257/test, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
Dec 21, 2019 9:12:50 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@71377f6e -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
org.postgresql.util.PSQLException: ERROR: password authentication failed for user daniel
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

Dec 21, 2019 9:12:50 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3f04d683 is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
Dec 21, 2019 9:12:50 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@d957d47 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
org.postgresql.util.PSQLException: ERROR: password authentication failed for user daniel
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

Dec 21, 2019 9:12:50 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3f04d683 is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
Syntax error (PSQLException) compiling def at (form-init6337712701184487046.clj:67:26).
ERROR: password authentication failed for user daniel
Dec 21, 2019 9:12:51 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@76d1637 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
org.postgresql.util.PSQLException: ERROR: password authentication failed for user daniel
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

Dec 21, 2019 9:12:51 PM com.mchange.v2.resourcepool.BasicResourcePool 
WARNING: Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@3f04d683 is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.

```

This time, Hikari works but C3P0 fails because it uses the wrong username. If compatibility is to be maintained with `clojure/java.jdbc` I would guess either `:user` needs to be explicitly remapped from the `db-spec` or a different alternative to `clojure.java.data/to-java` might be necessary since there is no guarantee that the attributes being set in the `db-spec` match the getter/setter patterns in the delegate connection pool classes.

**Comment by danielkyu** [comment]
Ah crap, I just read your response after I drafted that and hit comment. Apologies. I should have read the documentation more thoroughly. OTL

**Comment by seancorfield** [comment]
That is exactly what the documentation says. The argument to the `->pool` is used to set properties on the connection pool object. HikariCP and c3p0 name their properties differently. Since you can, in theory, use an arbitrary connection pooling library, `next.jdbc` has no control over the properties that the datasource object expects.

**Comment by danielkyu** [comment]
Yup! You're absolutely right. Thanks for the quick response. I'm still getting readjusted with Clojure and was skimming through a bunch of documentation between different blog posts, libraries and such. Still was a good experience though and came out learning a few new things. Hope I didn't consume too much of your time!

**Comment by seancorfield** [comment]
No problem! If I can make the documentation clearer, let me know. Welcome to Clojure!

If you're not already, I'd recommend joining the Clojurians Slack -- sign up at http://clojurians.net/
